# Traefik configuration file
# Traefik version: 3.4.0
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# EntryPoints configuration

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
  traefik:
    address: ":8080"

certificatesResolvers:
  myresolver:
    acme:
      email: bhojkamal@yahoo.com
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: ERROR
  filePath: /var/log/traefik/error.log
  format: common

accessLog:
  filePath: /var/log/traefik/access.log
  format: common

api:
  insecure: true
  dashboard: true
  debug: true

ping:
  entryPoint: web

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false

  file:
    directory: /etc/traefik
    watch: true
